data/articles.json

feat: update with recent articles

---

components/Layout/Footer.jsx

feat: add socials

---

components/Layout/Footer.jsx

feat: add coingecko

---

components/BondsPage/HowItWorks.jsx
components/BondsPage/index.jsx
components/DevRewardsPage/GetStarted.jsx
components/OlasTokenPage/TokenDetails.jsx
components/ui/table.jsx
components/ui/typography.jsx
pages/bonds.js

Implements these tickets:
- https://trello.com/c/fqYdScxT/1416-update-network-section-of-the-olas-site
- https://trello.com/c/P1dfeLVc/1417-add-more-details-on-bonding-page-https-olasnetwork-bonds

update TokenDetails with table and Arbitrum data

---

components/OlasTokenPage/TokenDetails.jsx

Both POS Bridge links point to https://portal.polygon.technology/bridge

revert bridge details

---

components/OlasTokenPage/TokenDetails.jsx

Update Arbitrum token details

---

components/OlasTokenPage/TokenDetails.jsx

- reverts to correct bridge names and links on Token Details table

Update bridge URLs in TokenDetails.jsx

---

components/BuildPage/BuildWithOlas.jsx
components/BuildPage/Hero.jsx

- used Button component for external links
- added docs link

Update build page buttons

---

components/Layout/Header.jsx
components/LearnPage/2WhatIsOlas/index.jsx
components/LearnPage/4HowDoOlasWork/index.jsx
components/LearnPage/5QuickIntroArticles/index.jsx
components/LearnPage/6WhyBuildOnOlas/index.jsx
components/LearnPage/index.jsx
components/Meta.jsx

slight improvements to learn page ui where there is non uniformity, missing content, or missing styling.

Learn page UI

---

data/services.json
pages/services/[slug].jsx

- added an additional button to AI Mechs service page at the request of Adriano
`/services/ai-mechs`

added additional button to AI Mechs service page

---

components/OlasTokenPage/index.jsx

Resolves the missing data on `/olas-token#get-olas`
Preview: https://olas-website-git-olastoken-epoch-fix-autonolas.vercel.app/olas-token#supply

Update epoch parameter in mapEpochTokenomics

---

components/Layout/SectionWrapper.jsx

Some backgrounds and images were lost with the last changes
| Broken      | Fixed |
| ----------- | ----------- |
| <img width="1679" alt="image" src="https://github.com/valory-xyz/olas-website/assets/22725775/b87ff3ab-364c-402e-bbbf-ac2fb36b2eb7">      | <img width="1680" alt="image" src="https://github.com/valory-xyz/olas-website/assets/22725775/d247f9f5-1b76-468a-91a5-008609bba6c2">       |
| <img width="1680" alt="image" src="https://github.com/valory-xyz/olas-website/assets/22725775/8c70e969-4a50-4d42-8b2a-6997e9b390b4">   | <img width="1680" alt="image" src="https://github.com/valory-xyz/olas-website/assets/22725775/bc0527ee-2557-44e8-be31-7937747269b7">        |

Fix missing backgrounds

---

components/OlasTokenPage/TokenDetails.jsx

- added token details for Optimism token and LP
token details: https://olas-website-git-olas-optimism-updates-autonolas.vercel.app/olas-token#supply
lp details: https://olas-website-git-olas-optimism-updates-autonolas.vercel.app/bond

Add Optimism token details

---

components/OlasTokenPage/TokenDetails.jsx

Added Base token and bond details
**Token**: https://olas-website-git-add-base-token-details-autonolas.vercel.app/olas-token#get-olas
**Bond**: https://olas-website-git-add-base-token-details-autonolas.vercel.app/bond#bonding-details

Add Base token details to TOKEN_DETAILS

---

components/OlasTokenPage/index.jsx

Fix inflation for year getting result

---

components/BuildPage/Opportunities.jsx

https://olas-website-git-fix-opportunities-fix-cta-autonolas.vercel.app/build#opportunities

Change CTA name

---

next.config.js

https://olas-website-git-feat-press-kit-redirect-autonolas.vercel.app/brand-and-press-kit

Add redirect for brand-and-press-kit

---

components/OperatePage/InstallRunAnAgent.jsx

feat: Update Pearl copy

---

common-util/graphql/client.js
common-util/graphql/queries.js
common-util/numberFormatter.js
components/OlasTokenPage/EmissionsToDevs.jsx
components/OlasTokenPage/LegendItem.jsx
components/OlasTokenPage/index.jsx
package.json
yarn.lock

https://olas-website-git-tanya-emissions-to-devs-autonolas.vercel.app/olas-token

feat: add emissions to devs chart

---

common-util/charts.js
common-util/graphql/queries.js
common-util/web3.js
components/OlasTokenPage/EmissionsToBonders.jsx
components/OlasTokenPage/EmissionsToDevs.jsx
components/OlasTokenPage/index.jsx

in this PR I also updated the emissions to devs chart styles (as agreed with Roman) + did some refactoring
https://olas-website-git-tanya-emissions-to-bonders-autonolas.vercel.app/olas-token

feat: add emissions to bonders chart

---

components/Meta.jsx

Update meta title and description

fix: update meta title and description

---

components/Layout/PageWrapper.jsx
components/ProtocolPage/ProtocolKeyFeatures.jsx

1) Updated banner text 
2) Removed extra space

chore: update banner text, remove extra space

---

.github/pull_request_template.md
components/OperatePage/InstallRunAnAgent.jsx
components/ui/button.jsx

feat: re-activate intel download

---

common-util/constants.js
components/OperatePage/FAQ.jsx
components/OperatePage/utils.js
data/affordances.json
pages/services/babydegen.jsx
pages/services/prediction-agents.jsx

Update all operate links so that they open /agents page in new operate app

feat: update operate links

---

components/HomepageSection/Activity.jsx

feat: Site updates

---

next.config.js

Add redirects from old tokenomics app

chore: add redirects from tokenomics app

---

common-util/api/flipside.js

fix: agent numbers

---

components/Layout/SectionWrapper.jsx
pages/services/babydegen.jsx

Reformatted /babydegen page style in line with the new Figma wireframe. Changed headings, text, hero buttons, further resources cards and some of the layout. 
before:
https://github.com/user-attachments/assets/a6ddcb96-7035-4833-9610-05452408b801
after:
https://github.com/user-attachments/assets/67530858-9b88-4c47-9797-5c666b6aa125

style: updates to babydegen page

---

components/OlasTokenPage/TokenDetails.jsx

Add celo to the Token Details list

feat: add celo to olas-token page

---

components/HomepageSection/TheTech.jsx
components/HomepageSection/UseCases.jsx

1) Commented out the hexagon **Expanding what's possible** section (we plan to move it to the explore page)
2) Updated styles and content in "the tech" section on home page

style: restyle the tech section

---

components/BuildPage/Hero.jsx
components/BuildPage/NewToOlas.jsx
components/HomepageSection/UseCases.jsx
components/MechPage/GetInvolved.jsx

Build page changes:
* Changed button text for Valory structured programs
* Redirected "Get started" button to "Two ways to grow" section
Mech page change:
* Link on "Get involved" section for builders disabled and changed to Coming soon

style: small changes to website

---

common-util/api/dune.js
common-util/constants.js
components/MechPage/MechAgentMetrics.jsx
components/MechPage/MechHero.jsx
components/MechPage/WhatIsOlasMech.jsx

Added metrics for mech page: predict, contribute, governatooor and other.
Before:
After:

feat: mech metrics

---

common-util/api/dune.js
common-util/constants.js
components/MechPage/MechAgentMetrics.jsx

Fix for DAA metric and renaming of getMechRqs -> getMechTxs.

fix: mech and DAA fixes

---

components/PredictPage/PredictHero.jsx

Added secondary button to predict hero linking to predict UI.

style: added link to predict ui from predict page

---

components/Content/Articles.jsx
components/Content/Updates.jsx
data/resources.json
pages/blog/index.jsx
pages/quarterly-updates.jsx
pages/quarterly-updates/index.jsx

New quarterly updates page. Folder added in blogs page that leads to q updates and added to resources drop down.

feat: added quarterly updates page

---

components/FAQPage/index.jsx

Added/modified faq page according to new design and doc. Also subheadings.
Before:
After:

feat: faq page updates

---

components/AUPage/Content.jsx
components/AUPage/Hero.jsx
components/Layout/Footer.jsx
data/friends.json
pages/blog/[id].jsx
styles/globals.js

* Fixed formatting issues with certain blog posts: headings and lists
* Added new resource links, AU and quarterly updates, to footer
* Fixed text on AU page in hero and middle content.
Before:
After:

style: website updates

---

components/BuildPage/WhatBuildersAreSaying.jsx
components/HomepageSection/Activity.jsx
components/OperatePage/OperateMetrics.jsx

* Made no of blockchains on homepage dynamic based on displayed amount on propelledBy section
* Corrected DAA metric on operate page
* Fixed alprina quote on builders page
No. of blockchains:
DAA metric on operate:
Alprina quote on build page:

chore: website fixes - metrics and quotes

---

components/AUPage/CTA.jsx

Added replay link and updated Bangkok card in AU page.
Before:
After:

style: updated AU Bangkok card

---

components/BuildPage/WhatBuildersAreSaying.jsx
components/LaunchPage/WhatLaunchersAreSaying.jsx

* Added links to case study posts

style: added links to case studies for quote cards

---

components/OlasTokenPage/UsagePieChart.jsx

chore: uncomment epoch data

---

components/FAQPage/index.jsx

Added 2 new questions to FAQ page.

style: added 2 new faqs

---

components/OptimusPage/TheProcess.jsx

Fixed mobile responsiveness for optimus page.
Before:
After:

fix: optimus mobile responsiveness

---

common-util/api/dune.js
common-util/constants.js
components/ContributePage/ContributeMetrics.jsx
components/GovernPage/WhyBecomeGovernor.jsx
components/HomepageSection/TheTech.jsx

* Updated Daily Active Contributors metric to use dune query, total contributors metric still static but updated to current amount
* Added links: govern page to roadmap, homepage tech section to staking

style: site updates

---

components/BuildPage/NewToOlas.jsx
data/academyMetrics.json
pages/mech-marketplace.jsx
styles/globals.css

Added academy metrics to build page and empty mech-marketplace page.

style: added academy metrics table

---

components/HomepageSection/Activity.jsx
components/PredictPage/Activity.jsx

Fix for this issue on home page and predict

fix: metrcis alignment

---

components/BuildPage/NewToOlas.jsx
components/MechPage/MechAgentMetrics.jsx
components/MechPage/MechHero.jsx
components/MechPage/WhatIsOlasMech.jsx
components/MechPage/WhyOlasMech.jsx
pages/services/ai-mechs.jsx

Text changes to services/ai-mechs and agent-economeies/mechs. Also academy table in /build.

style: mech page updates

---

components/AUPage/Content.jsx
components/BondsPage/HowBondingWorks.jsx
components/BuildPage/NewToOlas.jsx
components/Content/Updates.jsx
components/ExplorePage/UseCases.jsx
components/FAQPage/index.jsx
components/LearnPage/QuickIntroArticles.jsx
components/ProtocolPage/ProtocolAudits.jsx
components/ProtocolPage/ProtocolKeyFeatures.jsx
components/StackPage/StackKeyFeatures.jsx
data/resources.json

Changes to text for better tone and consistent formatting on following pages:
* AU
* Bond
* Q Updates
* Explore
* FAQ
* Stack
* Protocol
* Learn
Also fixed hydration error on build page academy metrics table.

style: fixing text inconsistencies

---

components/Services/BabyDegenPage/MeetTheBabyDegens.jsx
pages/services/agentsfun.jsx

feat: updates for Pearl release

---

components/Layout/PageWrapper.jsx

feat: update banner

---

pages/bottle.jsx

- `/bottle` [link](https://olas-website-git-mohan-bottle-autonolas.vercel.app/bottle)

feat: add Bottle link

---

components/OlasTokenPage/TokenDetails.jsx

feat: add exchange details for Mode token on TokenDetails page

---

components/AUPage/index.jsx
components/BuildPage/NewToOlas.jsx

* updated AU stats
* removed academy table from build

style: numbers update to AU page and removed academy table from build

---

components/OlasTokenPage/TokenDetails.jsx

feat: update bridge link for base

---

common-util/constants.js
pages/services/prediction-agents.jsx

DO NOT MERGE
update QS links in accordance with https://trello.com/c/kTXQCets/2331-existing-traders-qs-users-can-run-the-same-agents-using-the-new-qs

feat: update trader QS links

---

components/Services/BabyDegenPage/MeetTheBabyDegens.jsx

DO NOT MERGE
update QS links in accordance with https://trello.com/c/U9KJWIU3/2361-existing-non-traders-qs-users-can-run-the-same-agents-using-the-new-qs

feat: update non-trader QS links

---

components/AUPage/CTA.jsx

Updates to video links for each Agents Unleashed event in /agents-unleashed.

chore: updated AU video links

---

components/AUPage/CTA.jsx

Added ETHDenver 2025 replay link.

chore: added ETHDenver '25 link

---

common-util/constants.js
components/Layout/Header.jsx
components/Layout/MenuMobile.jsx
data/resources.json

Changes to Olas navbar:
* Different buttons to different links
* 'Get involved' button -> 'Own your agent' and now leads to /operate
* More resources menu changes

style: rearranging of navbar and links

---

components/AcceleratorPage/EvaluationCriteria.jsx

Changes to text in Evaluation Criteria section of /accelerator page.

style: accelerator eval criteria changes

---

data/useCases.json

Added AI mechs to "Use Cases" section on homepage.

style: added ai mechs to live use cases section

---

components/HackathonPage/CatchTheNextEvent.jsx

Added Prediction Agent card for Catch the Next Event section on /hackathons.

Style: added Prediction Agent hackathon

---

components/HackathonPage/CatchTheNextEvent.jsx
components/HackathonPage/Hero.jsx
components/HackathonPage/HowItWorks.jsx
components/HackathonPage/WhatCanYouBuild.jsx
components/HackathonPage/WhyParticipate.jsx

Hackathons page: 
* Text changes
* Title changes
* Links to different page

style: hackathon page updates

---

next.config.js
pages/_app.jsx

Added parameters for Plausible to more accurately track campaign performance (source, medium, campaign) and monitor real-time visits via UTM parameters.

chore: added specifics for plausible analytics

---

common-util/Accordion.jsx
components/Layout/Footer.jsx
components/OperatePage/FAQ.jsx
components/TimelinePage/Content.jsx
components/TimelinePage/Header.jsx
data/resources.json
data/timeline.json
pages/timeline.jsx
styles/globals.css

Added new timeline page on /timeline.

feat: timeline page

---

components/HomepageSection/Activity.jsx
components/OperatePage/Hero.jsx
components/OperatePage/MeetPearl.jsx
pages/operate.jsx

Text changes in homepage and operate for SEO.

style: SEO text updates on operate and homepage

---

common-util/api/dune.js
common-util/constants.js
components/MechPage/FeeMetrics.jsx
components/MechPage/WhatIsOlasMech.jsx
components/MechPage/WhyOlasMech.jsx
hooks/index.js
package.json
pages/agent-economies/mech.jsx
pages/services/agentsfun.jsx
yarn.lock

* Mech marketplace II: improve mech marketplace dashboard to show fee flow
* Mech fees - make clear on site how they are collected; what level they are at (show don’t tell); how this connects to Olas burn
Added Sankey diagram to mech marketplace page.

style: display fee flows on MM

---

data/timeline.json

New quarters added to Olas timeline.

style: added new quarters to timeline

---

pages/services/agentsfun.jsx

Text changes to /services/agentsfun page.

style: agents fun text changes for seo

---

components/HomepageSection/Hero.jsx
components/HomepageSection/OwnYourAgent.jsx
components/Layout/Header.jsx
components/Layout/MenuMobile.jsx
components/Layout/PageWrapper.jsx

Added Pearl links to any mention of "Own your agent".

chore: own your agent to link to pearl

---

components/MechPage/FeeMetrics.jsx

Changed labels and added descriptions with popovers. Also id for links.
https://github.com/user-attachments/assets/3d652e12-cad4-4b5d-a136-be83163982d7

Style: MM fees label changes and popovers

---

components/PearlPage/FAQ.jsx
components/PearlPage/Hero.jsx
components/PearlPage/InstallRunAnAgent.jsx
components/PearlPage/MeetPearl.jsx

Small: text updates for Pearl page seo.

style: pearl page seo text change

---

components/Layout/PageWrapper.jsx

style: removed banner

---

components/Services/PredictionAgentsPage/GetInvolved.jsx

fix: discord URL update 

---

components/HomepageSection/Activity.jsx
components/HomepageSection/AgentsWorkingTogether.jsx
components/HomepageSection/Hero.jsx
components/HomepageSection/OwnYourAgent.jsx
components/HomepageSection/TokenAddress.jsx
components/HomepageSection/WorldOfAgents.jsx
components/ProtocolPage/ProtocolAudits.jsx
styles/globals.css

Homepage layout fixes:
* Hero text align center on 4k screens
* agent carousel width limit on 4k screens
* mobile screen buttons on token address section
* Mobile headers
+ Cantina audit

style: layout fixes and cantina audit

---

components/AUPage/index.jsx
components/AboutPage/CoownershipOfAi.jsx
components/AboutPage/FoundingMembers.jsx
components/AboutPage/OlasStory.jsx
components/AboutPage/UniqueEdge.jsx
data/timeline.json

ABOUT - Typos fixed
AU - Changed numbers below fold to reflect ethcc
TIMELINE - added q2

style: changes made to about, au and timeline

---

data/agents.json
data/useCases.json

display "deprecated" tag on https://olas.network/agents/governatooorr and move to deprecated use cases page https://olas.network/deprecated-usecases.

fix: deprecate governatooorr

---

components/Content/Article.jsx

Fixes invalid date issue on article's card.

fix: invalid date bug

---

common-util/api/dune.js
pages/api/dune.js

We are running out of limits using Dune api keys, this PR adding 12hours caching for all queries

fix: add caching for dune queries

---

common-util/api/dune.js

Found out that /agent-economies/predict is broken

fix: api endpoint for dune

---

pages/api/dune.js

1) introduce a variable for dune cache hours, set it to 36 as we're running out of limits again

feat: make cache value a variable

---

common-util/constants.js
components/GovernPage/ShapeTheFuture.jsx

fix: proposals link & text

---

common-util/api/index.js
common-util/graphql/queries.js
components/AgentEconomies/BabydegenEconomyPage/BabydegenMetrics.jsx
components/AgentEconomies/MechPage/FeeMetrics.jsx
components/AgentEconomies/MechPage/MechAgentMetrics.jsx
components/AgentEconomies/MechPage/MechHero.jsx
components/DataPage/DailyActiveAgents.jsx
pages/api/babydegen-metrics.js
pages/api/mech-metrics.js
pages/data/index.jsx

* Added DAAs to agent-economies/babydegen and /mech

feat: added DAAs to mech and babydegen economy pages

---

pages/agents/ai-mechs.jsx

Fixed  buttons on /ai-mechs page.

style: fix ai mechs buttons

---

common-util/constants.js
components/Agents/WhatMakesOlasAgentsUnique.jsx
components/BuildPage/Content.jsx
components/BuildPage/Hero.jsx
components/Layout/Footer.jsx
pages/agents/ai-mechs.jsx

update registry/mech links to marketplace

feat: update registry/mech links to marketplace

---

components/AUPage/CTA.jsx

style: remove text

---

common-util/calculate7DayAverage.js
pages/api/babydegen-metrics.js
pages/api/main-metrics.js
pages/api/mech-metrics.js

Change how bbdg and mech avg agent activities are calculated:
* Avgs are calculated from each chain
* Added together as a total
Before:
After:

chore: change how bbdg and mech 7 day avgs work
